### ISSUE TITLE
World Generation Bugged

### ISSUE THREAD

**Issue by literally1984** [hpfxd/PandaSpigot#102]
Hello, a player on my server just reported strange world generation. There are random chunks popped out of the world, land that is cut in half, and other horrible things. I find this odd because my server has no world generation plugins installed and never has. If it is of any use, the world generation glitch only occurs on the positive x-axis thousands of blocks out. Also, my server migrated from 1.5.2 to 1.8.8 a few months ago, so maybe that has an impact (keep in mind that the glitched chunks are new chunks, though)? The only reason that I can think of for this weird chunk generation is that the server was running low on ram while the player was reporting this stuff. However, I went to the place where the glitched chunks were reported after a server restart and the chunk generation is still glitched :/.

![image](https://user-images.githubusercontent.com/85363779/222869559-d452031c-29c0-4e13-8248-c69af78fab2b.png)
![sad](https://user-images.githubusercontent.com/85363779/222869615-ee5eb2a8-6907-4ade-85a9-ec817e24bd3a.png)
![more_chunnk_glitch](https://user-images.githubusercontent.com/85363779/222869622-e3947eb8-4e91-4fdb-95de-e888a17212b7.png)
![Chunk_Error](https://user-images.githubusercontent.com/85363779/222869629-5a47b8c8-ddac-4787-b1db-5f177ad19b94.png)
![image](https://user-images.githubusercontent.com/85363779/222869670-fca4bad7-e948-449c-b288-23845109da02.png)

**Comment by iamnoksio** [comment]
> Hello, a player on my server just reported strange world generation. There are random chunks popped out of the world, land that is cut in half, and other horrible things. I find this odd because my server has no world generation plugins installed and never has. If it is of any use, the world generation glitch only occurs on the positive x-axis thousands of blocks out. Also, my server migrated from 1.5.2 to 1.8.8 a few months ago, so maybe that has an impact (keep in mind that the glitched chunks are new chunks, though)? The only reason that I can think of for this weird chunk generation is that the server was running low on ram while the player was reporting this stuff. However, I went to the place where the glitched chunks were reported after a server restart and the chunk generation is still glitched :/.

it's indeed the version change, 1.5.2 chunk generation isnt the same as 1.8.9 one

**Comment by literally1984** [comment]
> > Hello, a player on my server just reported strange world generation. There are random chunks popped out of the world, land that is cut in half, and other horrible things. I find this odd because my server has no world generation plugins installed and never has. If it is of any use, the world generation glitch only occurs on the positive x-axis thousands of blocks out. Also, my server migrated from 1.5.2 to 1.8.8 a few months ago, so maybe that has an impact (keep in mind that the glitched chunks are new chunks, though)? The only reason that I can think of for this weird chunk generation is that the server was running low on ram while the player was reporting this stuff. However, I went to the place where the glitched chunks were reported after a server restart and the chunk generation is still glitched :/.
> 
> it's indeed the version change, 1.5.2 chunk generation isnt the same as 1.8.9 one

Yeah I get that but keep in mind that my server switched versions a while ago and nobody's reported any chunks like these. I've personally loaded new 1.8.8 chunks back when I switched and this issue did not appear then

**Comment by iamnoksio** [comment]
> 

I get it, those chunks were simply loaded in 1.5.2 or not loaded in 1.5.2 ans loaded in 1.8

**Comment by MachineBreaker** [comment]
This happens because 1.7 and newer versions uses an entirely different chunk loader and the data isn't compatible

**Comment by iamnoksio** [comment]
> This happens because 1.7 and newer versions uses an entirely different chunk loader and the data isn't compatible

exactly what I've said lmao
