### ISSUE TITLE
Weird knockback

### ISSUE THREAD

**Issue by daniel-skopek** [hpfxd/PandaSpigot#109]
Using PandaSpigot, there is a different (weird) knockback on the server as opposed to Paper 1.8.8. Maybe this is due to a custom knockback setting?

**Comment by im-a-blobfish** [comment]
it might use kohi-like knockback values by default - you can change them in pandaspigot.yml

**Comment by Farmeurimmo** [comment]
Patch : https://github.com/hpfxd/PandaSpigot/blob/master/patches/server/0015-Configurable-knockback.patch
From : https://gist.github.com/YoungOG/e3265d98661957abece71594b70d6a01

**Comment by uRyanxD** [comment]
Latest build contains default knockback settings now, other knockback related issues should be investigated later
