### ISSUE TITLE
Question about setup to start contributing

### ISSUE THREAD

**Issue by PrismoidNW** [hpfxd/PandaSpigot#11]
Hello everyone, 
As you can probably see in the title, my question is about how do I start to contribute? I cloned the project into Intellij IDEA, ran the panda script by right clicking, then run panda and it did absolutely nothing. I appreciate it your going to help, maybe I'm missing something, I don't know. Thanks!

**Comment by uRyanxD** [comment]
Hi! For you to run Panda scripts you need:

JDK 8 (or above)
git
Maven
Bash

After cloning the project you have to type /panda build and wait, after the script runs it will generate the PandaSpigot-API and PandaSpigot-Server for you to modify.

**Comment by hpfxd** [comment]
> `./remap.sh: line 75: mvn: command not found`

Looks like you need to install Maven.

**Comment by PrismoidNW** [comment]
It is installed though, I installed it through Intellij

**Comment by hpfxd** [comment]
It needs to be accessible on your $PATH, I'm not sure if IntelliJ does this by default. [Here are the official installation instructions.](https://maven.apache.org/install.html)

**Comment by PrismoidNW** [comment]
Hello again, I installed Maven and ran ./panda patch and once again an error happened again: https://pastebin.com/jWq5ZsE1

**Comment by mechoriet** [comment]
> Hello again, I installed Maven and ran ./panda patch and once again an error happened again: https://pastebin.com/jWq5ZsE1

run ```./panda setup``` (to prepare paper to apply the patches too)  first before running ```./panda [apply/patch]```

**Comment by PrismoidNW** [comment]
Sorry if I may be misunderstanding, but I did run ./panda setup and ./panda patch, and I did get 2 errors: https://pastebin.com/Spi6AhpZ, as well as the one before (https://pastebin.com/jWq5ZsE1).

**Comment by mechoriet** [comment]
``` ./decompile.sh: line 23: jar: command not found ```

seems like it can't find the jdk to compile the mojang jar before patching paper

**Comment by PrismoidNW** [comment]
> `./decompile.sh: line 23: jar: command not found`
> 
> seems like it can't find the jdk to compile the mojang jar before patching paper

I can patch it with java 17 right? I might have to switch if I can't

**Comment by uRyanxD** [comment]
> > `./decompile.sh: line 23: jar: command not found`
> > seems like it can't find the jdk to compile the mojang jar before patching paper
> 
> I can patch it with java 17 right because isn't it java 8+? I might have to switch if I can't

Just using java 8 if I remember correctly

**Comment by uRyanxD** [comment]
> I mean am I able to compile to a more recent version of java?

Yes you can

**Comment by uRyanxD** [comment]
I'm closing this issue because the questions have been answered, if you have any more please reopen the issue or ask on Discord
