### ISSUE TITLE
NPCs don't like PandaSpigot

### ISSUE THREAD

**Issue by uRyanxD** [hpfxd/PandaSpigot#118]
Steps to craft:
1- Create an NPC using Citizens 
2- Go away from the NPC (until you don't see the NPC anymore) 
3- Go back to where the NPC is and he will be gone

Note: I tested the same server with Paper and it works normally
Video: https://www.youtube.com/watch?v=k2f-pWgpEUA
My Server Test: https://www.mediafire.com/file/hjr2c1gov7mpkaa/factions+-+Copia.zip/file

Potentially reported on: #6 , #27

**Comment by HanielCota** [comment]
I also noticed that citizens don't work on panda with some plugin stores like yStore, Storm etc etc, the npc skin simply doesn't work and you have to keep setting it manually, which no longer happens in other forks

**Comment by uRyanxD** [comment]
I noticed that sometimes it works normally, I reduced the number of server plugins and only left the basic ones (Vault, ProtocolLib, System (for /fly), etc), and the problem persists, download the new version: https://www.mediafire.com/file/el6vqfytosm2oui/factions+-+Copia.zip/file

**Comment by mechoriet** [comment]
seems something funky with flushing of packets 
in one of these patches 
![image](https://user-images.githubusercontent.com/4313219/232594805-bf46a06a-2b87-41bf-9c6d-7121ebc95bc3.png)
but overlooked a few so far they seems to be identical to other forks and paper with the minor adjustment for versions
