### ISSUE TITLE
Wrong order and white nickname of players in TAB

### ISSUE THREAD

**Issue by DrakMC** [hpfxd/PandaSpigot#12]
When using the https://github.com/NEZNAMY/TAB plugin, some players have white nicknames and are incorrectly sorted. For NachoSpigot this works without a problem.

**Comment by hpfxd** [comment]
Can you share your full list of plugins? I've been using TAB for months on multiple servers of mine using PandaSpigot and it works fine.

**Comment by DrakMC** [comment]
PlaceholderAPI, spark, ViaVersion, HolographicDisplays, ProtocolLib, LuckPerms, SkinsRestorer, BungeeGuard, Intave, Vault, TAB

**Comment by FiveMJerry** [comment]
Getting a similar issue with sorting not working properly via TAB. It works fine until the sorting type I has changes for the player then it does not update the list properly.

**Comment by jose27iwnl** [comment]
Any feedback? @hpfxd or @uRyanxD  maybe close this?

**Comment by uRyanxD** [comment]
I also cannot reproduce the problem, closing this issue
