### ISSUE TITLE
Help please, project not indexing my modules

### ISSUE THREAD

**Issue by egorsgn** [hpfxd/PandaSpigot#133]
Hello, I'm trying to build a project, the development environment reports the following
![изображение](https://user-images.githubusercontent.com/73982770/236320895-1fa957a0-0e37-4952-ad40-d9171f64e187.png)

**Comment by jose27iwnl** [comment]
That's weird
Can u build it without IDE
Using command?

**Comment by uRyanxD** [comment]
It doesn't seem to be a problem with PandaSpigot but with IntelliJ, if the folder name is not the same as rootProject.name in gradle it will send this error. https://youtrack.jetbrains.com/issue/IDEA-317606/Changing-only-the-case-of-the-Gradle-root-project-name-causes-exception-while-importing-project-java.lang.IllegalStateException
