### ISSUE TITLE
LazyRunnable is deprecated

### ISSUE THREAD

**Issue by MachineBreaker** [hpfxd/PandaSpigot#145]
`Type check vs LazyRunnable receive an always-on performance hit for a common operation that users shouldn't pay if they won't use it.`

https://github.com/netty/netty/commit/de876d197a945e2b3a4a96b90a65c00611b77806

**Comment by andreasdc** [comment]
You can report it to Paper too
https://github.com/PaperMC/Paper/blob/master/patches/server/0710-Optimise-non-flush-packet-sending.patch

**Comment by MachineBreaker** [comment]
I didn't find the related patch in Paper so i reported it here, gonna do it later

**Comment by andreasdc** [comment]
You didn't report it?

**Comment by andreasdc** [comment]
This may be really useful to fix, because with the latest netty I think it removes LazyRunnable from working completely.

**Comment by MachineBreaker** [comment]
LazyRunnable shouldn't be added again unless you workaround the [JDK-8180450](https://bugs.openjdk.org/browse/JDK-8180450) bug. This indeed makes packet writing slow (from 880ms to 1450ms)

**Comment by andreasdc** [comment]
> LazyRunnable shouldn't be added again unless you workaround the [JDK-8180450](https://bugs.openjdk.org/browse/JDK-8180450) bug. This indeed makes packet writing slow (from 880ms to 1450ms)

I think you should report it to netty then, this feature is still available, but in a different method.

**Comment by MachineBreaker** [comment]
> > LazyRunnable shouldn't be added again unless you workaround the [JDK-8180450](https://bugs.openjdk.org/browse/JDK-8180450) bug. This indeed makes packet writing slow (from 880ms to 1450ms)
> 
> I think you should report it to netty then, this feature is still available, but in a different method.

Netty already provided a solution, not my job to implement it

**Comment by andreasdc** [comment]
What solution?

**Comment by MachineBreaker** [comment]
> What solution?

Override SingleThreadEventExecutor#wakesUpForTask
