### ISSUE TITLE
error multiverse

### ISSUE THREAD

**Issue by f3f5-dev** [hpfxd/PandaSpigot#159]
caused by pandaspigot. tested with flamepaper

https://pastes.dev/dizwwjyIgC

**Comment by uRyanxD** [comment]
This error is due to the removal of legacy mappings (More information in issue #7).
You can use this version of MultiverseCore (https://dev.bukkit.org/projects/multiverse-core/files/2428161) to avoid this error, it was made for 1.9 but works perfectly in 1.8
