### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by GronyRalph** [hpfxd/PandaSpigot#160]
My server has been stopping without reason lately, I tried removing every plugin but it still happens, look what it drops on the console:
https://paste.gg/p/anonymous/21254ba594e54bb2a3b2e9a6136346c3
it told me to post the issue here, hope you can help me

**Comment by codemarked** [comment]
SongPlayer.run() what does it do?

**Comment by GronyRalph** [comment]
> SongPlayer.run() what does it do?

It might be noteblockapi player, I'll try removing it

**Comment by GronyRalph** [comment]
> SongPlayer.run() what does it do?

I removed everything that could be related and it's still happening
https://paste.gg/p/anonymous/3e6fbc94a2014eba9339d61ff2d2ef99
I start the server and can join normally but if I log off and back in, it freezes, I see the void for a few seconds before it crashes and drops that in the console

**Comment by codemarked** [comment]
Man, I see you are using skript, remove every plugin one by one until you get no crash. Something might be wrong in whatever you do in those sk files, just write proper java please! Do yourself and your players a favour...

**Comment by GronyRalph** [comment]
> Man, I see you are using skript, remove every plugin one by one until you get no crash. Something might be wrong in whatever you do in those sk files, just write proper java please! Do yourself and your players a favour...

Sorry, it's still happening :(
https://paste.gg/p/anonymous/30f21913ab4c4df7b684ed22583c65c1

**Comment by codemarked** [comment]
Do a timings report after you start the server but let it run for a few minutes without joining. Send it here

**Comment by GronyRalph** [comment]
> Do a timings report after you start the server but let it run for a few minutes without joining. Send it here

Should I join while I do this?

**Comment by codemarked** [comment]
No joining

**Comment by GronyRalph** [comment]
> No joining

https://timings.aikar.co/dev/?id=4e4dea7099424f86aa7ee5990efeaabe

**Comment by codemarked** [comment]
Try removing citizens then join and see what happens

**Comment by codemarked** [comment]
Also you are going to need more ram for the amount of plugins you are using, You may have to use a different Aikar startup script for better GC. You have too many plugins, that is not how you make a server...

**Comment by GronyRalph** [comment]
I allocated 10 GB and removed Citizens, could you elaborate on the Aikar script? I haven't touched any of the PufferPanel parameters regarding it
https://paste.gg/p/anonymous/b4fd34ae1b8e40d590fc8d49529025d1
https://timings.aikar.co/dev/?id=956192dfebf2473e88cd4fa8771a6f18

**Comment by GronyRalph** [comment]
> Also you are going to need more ram for the amount of plugins you are using, You may have to use a different Aikar startup script for better GC. You have too many plugins, that is not how you make a server...

please
