### ISSUE TITLE
Wraith anticheat 

### ISSUE THREAD

**Issue by fanat1cc** [hpfxd/PandaSpigot#166]
Idk why this is happening ik it's something to do with protocollib but ik all of my plugins are compatible but I can't seem to fix this whenever I try and run ww testclient "player" it checks what client /mods a player is using
[latest.log](https://github.com/hpfxd/PandaSpigot/files/12782394/latest.log)

**Comment by codemarked** [comment]
plugin issue not spigot issue

**Comment by fanat1cc** [comment]
I figure but if anyone is going to understand why and can understand the log it would be this community

**Comment by uRyanxD** [comment]
Closing this issue due to it having already been answered on Discord.
