### ISSUE TITLE
Chat problems with 1.20.4 client

### ISSUE THREAD

**Issue by Askarionn** [hpfxd/PandaSpigot#175]
![image](https://github.com/hpfxd/PandaSpigot/assets/51824859/391b8df8-d99f-4bfb-875c-5be2296276c6)
Tested with 1.20.4 client

**Comment by Askarionn** [comment]
With 1.20.2 it doesn't happen

**Comment by GeorgeV220** [comment]
in 1.20.4 Mojang changed chat serialization. I suppose this needs to be fixed by ViaVersion

**Comment by jordoncodes** [comment]
the release version of ViaVersion doesn't properly support 1.20.4 yet, use a dev version of ViaVersion and see if it works

> ![image](https://private-user-images.githubusercontent.com/51824859/293407752-391b8df8-d99f-4bfb-875c-5be2296276c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzY1NDEsIm5iZiI6MTcwNTM3NjI0MSwicGF0aCI6Ii81MTgyNDg1OS8yOTM0MDc3NTItMzkxYjhkZjgtZDk5Zi00YmZiLTg3NWMtNWJlMjI5NjI3NmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAzMzcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3ZjY5MTBkZDhmZGZjYTBjNGJjOWY5ZDBjMTVlNDcyZDcwNjMyMWY4ZmJlOTAyMmE4ODNiYWIxYTExZGUzOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q9UEqNSqhnIh8YPLKZ-Lx9O7qhHA5lSZi9LXEw2ViYQ) Tested with 1.20.4 client
