### ISSUE TITLE
remove the spaces in Server JAR in Artifacts

### ISSUE THREAD

**Issue by postyizhan** [hpfxd/PandaSpigot#176]
Can you remove the spaces in Server JAR in Artifacts? I want to use curl to download, but because this space is not successful
```
set url="https://nightly.link/hpfxd/PandaSpigot/workflows/build/master/Server JAR.zip"
set zipfile="Server JAR.zip"
curl -L -o "%zipfile%" "%url%"
```
I have tried:
Use ' 'or " "
%20
\0
^

From translator

**Comment by uRyanxD** [comment]
^
