### ISSUE TITLE
Console color is black by default

### ISSUE THREAD

**Issue by Rabbit0w0** [hpfxd/PandaSpigot#183]
CraftChatMessage#fromComponent(IChatBaseComponent) works like this
![image](https://github.com/hpfxd/PandaSpigot/assets/21006278/d429f274-d24f-4c05-acbb-0985a3a87cf3)
you using a pretty innovative way to train users' eyesight

**Comment by Rabbit0w0** [comment]
ps: if you use vanilla commands like `op` and `gamemode` in console, you should notice this problem

**Comment by uRyanxD** [comment]
I hadn't seen this issue before, I will continue monitoring the problem in my issue #204
