### ISSUE TITLE
how 2 compile

### ISSUE THREAD

**Issue by nearfe** [hpfxd/PandaSpigot#197]

**Comment by jose27iwnl** [comment]
1º Use git clone command to clone the repository to your computer.
2º Go to the Directory and open a cmd or git bash if u have Git installed in your computer.
3º Do the command ./panda jar
If u can't finish the build, maybe change the java version to 1.8 in your system environment variables, should fix.
Or open a issue with the error log.

**Comment by uRyanxD** [comment]
Closing this issue, the question has already been answered above.
