### ISSUE TITLE
Suggestion: F3 server name

### ISSUE THREAD

**Issue by Askarionn** [hpfxd/PandaSpigot#26]
Add in configuration file the option to change the server-name in F3 details

**Comment by Permanently** [comment]
Already possible with [F3Name](https://www.spigotmc.org/resources/58997/).

**Comment by Askarionn** [comment]
> Already possible with [F3Name](https://www.spigotmc.org/resources/58997/).

I know but will be more easier if it's implemented in jar so we don't have to install plugins for every little thing

**Comment by Permanently** [comment]
It's the most pointless feature to add.

> PandaSpigot: Fork of Paper for 1.8.8 focused on improved performance and stability.

Adding a feature to customise the server name via F3 doesn't focus on either. If anything, it focuses on removing credit for PandaSpigot.

**Comment by uRyanxD** [comment]
I am closing this issue because all maintainers agree with Permanently
