### ISSUE TITLE
Issues with protocolsupport

### ISSUE THREAD

**Issue by adamj454545** [hpfxd/PandaSpigot#29]
Just a plugin incompatibility issue I noticed when trying out PandaSpigot on my server.

Tacospigot already has this issue fixed, and I think it was fixed in these commits.

https://github.com/TacoSpigot/TacoSpigot/commit/1ed1ff476881e2f8d6e93a72b0892cd18d26e87e
https://github.com/TacoSpigot/TacoSpigot/commit/2778432865668967642c3415ed81fdd74b79ea70
https://github.com/TacoSpigot/TacoSpigot/commit/c2835dfc212269558aee56dca364f926d75a4989

**Comment by ayunami2000** [comment]
I'll make these changes and PR it, give me a bit.

**Comment by uRyanxD** [comment]
After PR #30 is merged, I adapt the TacoSpigot patch and perform a PR
