### ISSUE TITLE
packet 0/75 (client boundsetchunk cache center packet)

### ISSUE THREAD

**Issue by haroldrc** [hpfxd/PandaSpigot#52]
when i try to access the server after reboot

![image](https://user-images.githubusercontent.com/29206120/204165892-34e67cc6-35f8-4af1-b47d-6f6e4221282a.png)

**Comment by uRyanxD** [comment]
What plugins are you using? Which client are you using?

**Comment by haroldrc** [comment]
![image](https://user-images.githubusercontent.com/29206120/206581939-78ea386e-08bf-4be7-8e6d-0c2b18702cc1.png)


I used the lunarclient (the error also occurs with the vanilla client). I have another server with the same jar version and it doesn't give me the error

**Comment by uRyanxD** [comment]
Closing this issue as it is not a problem with PandaSpigot, but with some plugin. Maybe ViaVersion? Or with some other BungeeCord/Velocity plugin (If you use any of those).
