### ISSUE TITLE
Patch backport request

### ISSUE THREAD

**Issue by uRyanxD** [hpfxd/PandaSpigot#8]
If you can add the patch (https://github.com/PaperMC/Paper/blob/ver/1.12.2/Spigot-Server-Patches/0030-Lighting-Queue.patch) I would appreciate it.

**Comment by hpfxd** [comment]
I've ported this patch to PandaSpigot, but I'm not exactly sure how this interacts with Paper 1.8's `use-async-lighting` option (this option isn't in 1.12).

I don't currently have enough time to look at/test this properly, so I'm not going to be adding it to PandaSpigot for the time being. [Here's the patch](https://gist.github.com/hpfxd/56e8a32f508bc02c5fc42a3bd82baa08) if you want to use it yourself, it may break things.
