### ISSUE TITLE
PlayerHandshakeEvent not firing

### ISSUE THREAD

**Issue by literally1984** [hpfxd/PandaSpigot#83]
My code for listening to the event was:
```
@EventHandler
    public void onHandshake(PlayerHandshakeEvent event) {
        System.out.println("AsyncPlayerPreLoginEvent fired!");
        System.out.println(event.getOriginalHandshake());
    }
```
Nothing was printed to console. Other events are working just fine so it (probably) isn't an issue on my end.

**Comment by literally1984** [comment]
This is definitely not just something on my end. The popular [BungeeGuard](https://www.spigotmc.org/resources/bungeeguard.79601/) plugin which relies on the PlayerHandshakeEvent also does not work on PandaSpigot.

**Comment by mechoriet** [comment]
```java
public final class Pandatest extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        PluginManager manager = this.getServer().getPluginManager();
        manager.registerEvents(this,this);

    }

    @EventHandler
    public void onHandshake(PlayerHandshakeEvent event) {
        System.out.println("AsyncPlayerPreLoginEvent fired!");
        System.out.println(event.getOriginalHandshake());
    }
}
```
for me this just fired 
```
[18:18:51 INFO]: AsyncPlayerPreLoginEvent fired!
[18:18:51 INFO]: [redacted](ip)
```
on latest build 82

**Comment by hpfxd** [comment]
unable to reproduce, the event seems to be firing fine when testing. if you're able to create a reproducible example, please re-open.
