### ISSUE TITLE
[Performance] Bad results of modern tickloop reported by spark

### ISSUE THREAD

**Issue by uRyanxD** [hpfxd/PandaSpigot#88]
Bad modern tickloop results reported by spark

My server test:
https://i.imgur.com/8UdZ7yL.png / https://spark.lucko.me/hgbbsePaCh

My friend server:
https://i.imgur.com/GRTTmdb.png / https://spark.lucko.me/PXnVGT7j3j

My other friend server:
https://i.imgur.com/7bO701C.png / https://spark.lucko.me/vw7Jcg95W0

**Comment by mechoriet** [comment]
looks perfectly normal cause it "waiting" the thread to wait the remaining time.
one tick is allowed to use 50ms before lag occurs
so 20 ticks results to 1000ms

cause now its visualized more what the wait period was and how much it used of it(well was waiting for the full 50ms) to pass before starting on the next tick

so for example if a tick takes 15ms it waits for 35ms before starting the next one to keep the fixed tickrate of 20

if you look at more modern servers(1.19/1.18) you will see the same result that waitUntilNextTick looks high but its just a park task to wait the time out


https://github.com/hpfxd/PandaSpigot/blob/master/patches/server/0004-Backport-modern-tick-loop.patch#L140-L143

to me this looks like normal behavior
