### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by Askarionn** [hpfxd/PandaSpigot#9]
Hi guys!
I switched to PandaSpigot and i have some tps issues.
I tested with PaperSpigot java 8 and the TPS is 20* without any settings/plugins.
When i installed PandaSpigot java 17 the tps was never 20, maximum 19.90 (without any settings/plugins).
If players join (maximum 10) the tps is 19.50-19,80. I tried to generate a spark profiler and it seems that updateTimeLightAndEntities is consuming 15% from tick.

**Comment by andreasdc** [comment]
> Hi guys! I switched to PandaSpigot and i have some tps issues. I tested with PaperSpigot java 8 and the TPS is 20* without any settings/plugins. When i installed PandaSpigot java 17 the tps was never 20, maximum 19.90 (without any settings/plugins). If players join (maximum 10) the tps is 19.50-19,80. I tried to generate a spark profiler and it seems that updateTimeLightAndEntities is consuming 15% from tick.

Can you post both profilers and run them with exact settings and for at least 5 minutes? Also make sure that entities are the same and they are doing the same actions during these tests.

**Comment by uRyanxD** [comment]
Maybe it's the same problem as reported in https://github.com/CobbleSword/NachoSpigot/issues/411

**Comment by Fejm** [comment]
https://github.com/Wind-Development/WindSpigot/commit/b735e19966c7119ce92e510f915d0c58de705374

**Comment by uRyanxD** [comment]
Possible fix for this (https://github.com/uRyanxD/PandaSpigot/blob/test2/patches/server/0062-Use-BigDecimal-to-improve-accracy-of-TPS-results.patch) making TPS more accurate, if you can build and test to see if it works

**Comment by Fejm** [comment]
> Possible fix for this (https://github.com/uRyanxD/PandaSpigot/blob/test2/patches/server/0062-Use-BigDecimal-to-improve-accracy-of-TPS-results.patch) making TPS more accurate, if you can build and test to see if it works

It will not work. Only modern tick loop can fix this issue.
