### ISSUE TITLE
Velocity Modern Forwarding Support

### ISSUE THREAD

**Issue by e-splat** [hpfxd/PandaSpigot#92]
since this is a mantained fork, it will be cool to see Modern Velocity Forwarding support like on 1.13 and above on 1.8.8

**Comment by uRyanxD** [comment]
I believe the modern speed forwarding system uses packets that only exist in 1.13+, so it's impossible

**Comment by hpfxd** [comment]
Closing this as it is not possible to implement, see above. Modern forwarding uses the [Login Plugin Request](https://wiki.vg/Protocol#Login_Plugin_Request) and [Login Plugin Response](https://wiki.vg/Protocol#Login_Plugin_Response) packets which were added in 1.13.
