### ISSUE TITLE
Issue with Tick Loop

### ISSUE THREAD

**Issue by DripW** [hpfxd/PandaSpigot#99]
I've done testing with the backported tick loop after having to remove it myself from a personal project. 

Just wanted to address that there's some side effects that I couldn't resolve that this caused. 

The main prominent issue encountered was a delay applied to every action. Hitting, Moving, Player Location, etc were all impacted and a noticeable delay is felt in combat or anything requiring you to have correct timing. 

Just something for you guys to look into.

**Comment by andreasdc** [comment]
Shouldn't the patch bring less delay and less difference between ticks?

**Comment by DripW** [comment]
> Shouldn't the patch bring less delay and less difference between ticks?

Yes, it should. But, I assume it's causing an issue that is too advanced and out of my range of knowledge. Maybe a desync of packet queue, no idea. All I know is, I've tested this on a plain Paper and Taco fork, and the issue persisted.

**Comment by andreasdc** [comment]
Issue persisted on taco and paper?
How did you check the "desync" or "delay"?

**Comment by DripW** [comment]
> Issue persisted on taco and paper? How did you check the "desync" or "delay"?

By doing the same tasks on all other versions, hitting a player, turning and throwing a pot, all those would give u a visual example of the delay.

**Comment by andreasdc** [comment]
Without pretty heave changes you will always have big delay, do you have a video or something? The best would be to compare execution times, but I doubt that this patch broke something. If you have it on paper and taco it shouldn't work like that, you can also try spigot, because there was some bug that caused wrong tick times.

**Comment by DripW** [comment]
> do you have a video or something? The best would be to compare execution times, but I doubt that this patch broke something. If you have it on paper and taco it shouldn't work like that, you can also try spigot, because there was some bug that caused wrong tick times.

Regardless, my point is, this issue doesn't exist without it. Therefore, it's the cause.

**Comment by HanielCota** [comment]
[02:44:30 WARN]: Can't keep up! Is the server overloaded? Running 12859ms or 257 ticks behind

**Comment by mechoriet** [comment]
perhaps #107 since it could feel like a delay with lots of connections and lots of packets since I guess this was during combat like pvp and you have a lot of movement change+swing actions

hopefully you can give it a try when its merged

**Comment by DripW** [comment]
> perhaps #107 since it could feel like a delay with lots of connections and lots of packets since I guess this was during combat like pvp and you have a lot of movement change+swing actions
> 
> hopefully you can give it a try when its merged

I'm curious, what type of profiling did you run to diagnose this issue? I'm very noobish with Netty and I'm not very much familiar with it's behavior, how does anyone go about finding this?
